version: '3.9'
services:
  app_service:
    container_name: nestjs_application_for_service_catalog
    build:
      context: .
    ports:
      - '3000:3000'
    environment:
      - DB_TYPE=postgres
      - PG_USER=postgres_user
      - PG_PASSWORD=postgres_password
      - PG_DB=service_catalog_pgdb
      - PG_PORT=5432
      - PG_HOST=database_service
    depends_on:
      - database_service

  database_service:
    container_name: postgres_db_for_service_catalog
    image: postgres:15
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: service_catalog_pgdb
    ports:
      - '5432:5432'
    volumes:
      - my_pg_data:/var/lib/postgresql/data

volumes:
  my_pg_data: {}
